Merge working branch
eduardoreisalvarenga/HTML-Forms.github.io pull request #1
Opened 2019-07-24 03:27 UTC by davidauza-engineer

Let us know your comments about this branch

2019-07-24 04:16 UTC, Ispirett commented
Hey folks excellent work with this project you almost past on your first review  :1st_place_medal: 

## Sign up button
Please add the signup button and corresponding test within the right corner Thanks!

2019-07-24 04:22 UTC, Ispirett requested changes

2019-07-24 04:22 UTC, Ispirett commented on index.html
> +            <h1 class="signin-form">Sign In</h1>
Please replace this with **Create an Intuit account**

2019-07-24 17:47 UTC, davidauza-engineer commented
All changes done :)

2019-07-25 00:18 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-07-25 00:23 UTC, Torres-ssf commented
### Nicely Done team 👏
I'll give this project a 👍. Go on and merge to master. Good luck with the next one.

2019-07-25 15:18 UTC, merged